Project.new do |p|

    #Change this with your class prefix for Objective-C files.
    p.class_prefix = "APP"

    # By default Xcake defaults to creating the standard Debug and Release
    # configurations, uncomment these lines to add your own.
    #
    #p.debug_configuration :Staging
    #p.debug_configuration :Debug
    #p.release_configuration :Release

    # Change these to the platform you wish to support (ios, osx) and the
    # version of that platform (8.0, 9.0, 10.10, 10.11)
    #
    p.application_for :ios, 8.0 do |t|

        #Update these with the details of your app
        t.name = "YourApp"
        t.all_configurations.product_bundle_identifier = "com.yourcompany.yourapp"

        # Uncomment to target iPhone devices only
        #
        # File patterns can be seen here https://guides.cocoapods.org/syntax/podspec.html#group_file_patterns
        #
        #t.all_configurations.supported_devices = :iphone_only

        # Uncomment this to include additional files
        #
        #target.include_files << "FolderToInclude/*.*"

        # Uncomment this to exclude additional files
        #
        # File patterns can be seen here https://guides.cocoapods.org/syntax/podspec.html#group_file_patterns
        #
        #target.exclude_files << "ExcludeToInclude/*.*"

        # Uncomment to set your own build settings
        #
        #target.all_configurations.settings["ENABLE_BITCODE"] = "NO"
        #target.all_configurations.settings["GCC_PREFIX_HEADER"] = "APP-Prefix-Header.pch"
        #target.all_configurations.settings["SWIFT_OBJC_BRIDGING_HEADER"] = "APP-Bridging-Header.h"

        # Uncomment to define your own preprocessor macros
        #
        #target.all_configurations.preprocessor_definitions["API_ENDPOINT"] = "https://example.org".to_obj_c

        # Comment to remove Unit Tests for your app
        #
        p.unit_tests_for t

        # Uncomment to create a Watch App for your application.
        #
        #p.watch_app_for t, 2.0
    end
end
