name: Test

jobs:
  rvm:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15]
        ruby: [2.3.3, 2.4, 2.5, 2.6, 2.7]
        gemfile: [Gemfile]
        include:
          - os: ubuntu-latest
            ruby: 2.3.3
            gemfile: gemfiles/Gemfile.xcodeproj-edge
          - os: macos-10.15
            ruby: 2.3.3
            gemfile: gemfiles/Gemfile.xcodeproj-edge
    runs-on: ${{ matrix.os }}
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundler
      run: |
        bundle install --jobs=3

    - name: Test
      run: |
        export XCAKE_CI_TASKS=TEST
        bundle exec rake

  system-ruby:
    strategy:
      matrix:
        os: [macos-10.15]
        gemfile: [Gemfile]
        include:
          - os: macos-10.15
            gemfile: gemfiles/Gemfile.xcodeproj-edge
    runs-on: ${{ matrix.os }}
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - name: Bundler
      run: |
        bundle install --jobs=3
    - name: Print system Ruby version
      run: ruby -v

    - name: Test
      run: |
        export XCAKE_CI_TASKS=TEST
        bundle exec rake
on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main
  schedule:
    - cron:  '0 9 * * 0,1,2,3,4'
      branches:
      - main
